// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLBBoiOdAb1KXzqZbufH835S_nEs2uAWk',
    appId: '1:877143721861:web:768a4b2711d7a7a784e6ec',
    messagingSenderId: '877143721861',
    projectId: 'foodie-e5973',
    authDomain: 'foodie-e5973.firebaseapp.com',
    storageBucket: 'foodie-e5973.firebasestorage.app',
    measurementId: 'G-WZFM2V60WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuDip5FwiiMif_BcYXezCbxWs2OTt7xwk',
    appId: '1:877143721861:android:3eb48d3c7781122884e6ec',
    messagingSenderId: '877143721861',
    projectId: 'foodie-e5973',
    storageBucket: 'foodie-e5973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAsih4-7dicSEIcq6_cp45EP3ai5HxYUY',
    appId: '1:877143721861:ios:9288c73cfe6091ca84e6ec',
    messagingSenderId: '877143721861',
    projectId: 'foodie-e5973',
    storageBucket: 'foodie-e5973.firebasestorage.app',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAsih4-7dicSEIcq6_cp45EP3ai5HxYUY',
    appId: '1:877143721861:ios:9288c73cfe6091ca84e6ec',
    messagingSenderId: '877143721861',
    projectId: 'foodie-e5973',
    storageBucket: 'foodie-e5973.firebasestorage.app',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLBBoiOdAb1KXzqZbufH835S_nEs2uAWk',
    appId: '1:877143721861:web:f2dcbf94639038fb84e6ec',
    messagingSenderId: '877143721861',
    projectId: 'foodie-e5973',
    authDomain: 'foodie-e5973.firebaseapp.com',
    storageBucket: 'foodie-e5973.firebasestorage.app',
    measurementId: 'G-M260WHVT15',
  );
}
